"""
Training Guide for Simplexity
=============================

This script provides an annotated walkthrough of training a predictive model to predict
sequences generated by a Hidden Markov Model (HMM). It's designed to be readable
and educational - see run.py for the production version with type annotations.

Architecture Overview:
---------------------
1. GENERATIVE PROCESS (HMM): Produces sequences of tokens according to probabilistic
   state transitions. The model learns to predict these sequences. Can use built-in
   generators or custom ones (see matrices.py for an example).

2. PREDICTIVE MODEL: A model that learns to predict the next token given previous tokens.
   Supports HookedTransformer (transformer-lens) or custom models like RNN (see models/rnn.py).

3. TRAINING LOOP: Standard supervised learning - generate sequences from HMM,
   have model predict next tokens, compute cross-entropy loss, backprop.

4. ACTIVATION ANALYSIS: Periodically analyze model activations for analysis and plotting.
   Different models require different activation tracker configs (see configs/activation_tracker/).
"""

import logging
from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import jax
import jax.numpy as jnp
import mlflow
import torch
import tqdm

# this is to check model type for activation caching
# to handle both RNN and transformer models
from transformer_lens import HookedTransformer

import simplexity

# registers custom HMM matrix function, not used explicitly
# only necesarry when using custom generative processes
import matrices  

from simplexity.generative_processes.torch_generator import (
    generate_data_batch,
    generate_data_batch_with_full_history,
)

CONFIG_DIR = str(Path(__file__).parent / "configs")
CONFIG_NAME = "config.yaml"

# this supresses some warnings from databricks sdk
logging.getLogger("databricks.sdk").setLevel(logging.WARNING)


def _expand_init_state(initial_state, batch_size):
    """
    Replicate the HMM's initial state across the batch dimension.

    The generative process starts from a fixed initial state. To generate
    a batch of independent sequences, we need batch_size copies of this state.
    """
    if isinstance(initial_state, tuple):
        return tuple(jnp.repeat(s[None, :], batch_size, axis=0) for s in initial_state)
    return jnp.repeat(initial_state[None, :], batch_size, axis=0)


# ==============================================================================
# DECORATORS
# ==============================================================================
# @hydra.main: Injects 'cfg' argument from the contents of YAML files in configs/.
#               .
# @simplexity.managed_run: Instantiates objects from config.defaults
#                          (model, optimizer, etc.).
#                          Injects 'components' argument that holds them
# ==============================================================================

@hydra.main(config_path=CONFIG_DIR, config_name=CONFIG_NAME, version_base="1.3")
@simplexity.managed_run(strict=False, verbose=True)
def main(cfg, components):
    """
    Main training function.

    Args:
        cfg: Hydra configuration object with all settings from YAML files
        components: Simplexity component container (injected by @managed_run)
                   Provides pre-instantiated model, optimizer, logger, etc.
    """

    # ==========================================================================
    # COMPONENT RETRIEVAL
    # ==========================================================================
    # The @managed_run decorator instantiates all components from config.
    # We retrieve them here. Each component is configured in its own YAML file.

    active_run = mlflow.active_run()
    assert active_run is not None

    # Logger: Logs metrics and artifacts to (in this case) MLflow
    logger = components.get_logger()

    # Generative Process: The HMM that generates training sequences
    generative_process = components.get_generative_process()

    # Persister: Saves model checkpoints and registers models to (in this case) MLflow
    persister = components.get_persister()

    # Predictive Model: The transformer we're training
    predictive_model = components.get_predictive_model()

    # Optimizer: Updates model weights (e.g., Adam)
    optimizer = components.get_optimizer()

    # LR Scheduler: Adjusts learning rate during training
    learning_rate_scheduler = components.get_learning_rate_scheduler()

    # Metric Trackers: Compute and aggregate metrics (loss, lr, tokens seen, etc...)
    # We have separate trackers for training and evaluation
    # The keys are defined in the top level config.yaml
    training_metric_tracker = components.get_metric_tracker("training_metric_tracker")
    eval_metric_tracker = components.get_metric_tracker("eval_metric_tracker")

    # Activation Tracker: Analyzes transformer activations (PCA, regression, etc.)
    activation_tracker = components.get_activation_tracker()

    # Temporary directory for saving visualizations before uploading to MLflow
    visualization_path = TemporaryDirectory()

    # ==========================================================================
    # DATA GENERATION SETUP
    # ==========================================================================

    # The sequence length is derived from the model's context window (n_ctx),
    # minus any special tokens (BOS/EOS) that take up positions.
    # In order to support both RNN and transformer models, we
    # simply included a n_ctx field in the RNN config even though RNNs don't use it.
    context_len = cfg.predictive_model.instance.cfg.n_ctx
    bos_token = cfg.generative_process.bos_token
    eos_token = cfg.generative_process.eos_token
    sequence_len = context_len - int(bos_token is not None) - int(eos_token is not None)


    # Initialize batch_size copies of the HMM's starting state
    gen_states = _expand_init_state(
        generative_process.initial_state,
        cfg.training.batch_size,
    )

    # Handle device placement (MPS on Mac requires special handling since JAX
    # doesn't support MPS - JAX runs on CPU, PyTorch model on MPS)
    model_device = next(predictive_model.parameters()).device
    device_arg = model_device if model_device.type == "mps" else None

    # ==========================================================================
    # CORE FUNCTIONS
    # ==========================================================================

    def generate(step):
        """
        Generate a batch of sequences from the HMM.
        Returns (inputs, labels) where labels are inputs shifted by 1.
        NOTE: If on macOS with MPS, inputs are on MPS and labels on CPU.
        """
        key = jax.random.key(step)
        _, inputs, labels = generate_data_batch(
            gen_states,
            generative_process,
            cfg.training.batch_size,
            sequence_len,
            key,
            device=device_arg,
            bos_token=cfg.generative_process.bos_token,
        )
        return inputs, labels

    loss_fn = torch.nn.CrossEntropyLoss()

    def get_loss(outputs, labels):
        """
        Compute loss between model predictions and true next tokens.

        outputs: (batch, seq_len, vocab_size) - model's predicted logits
        labels:  (batch, seq_len) - true next tokens
        """
        return loss_fn(
            outputs.reshape(-1, outputs.shape[-1]),
            labels.reshape(-1).long().to(outputs.device)
        )

    def train_step(step):
        """
        Single training step: forward pass, loss computation, backward pass.
        Also tracks training metrics and updates learning rate.
        """
        predictive_model.train()
        inputs, labels = generate(step)
        outputs = predictive_model(inputs)
        loss = get_loss(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        training_metric_tracker.step(tokens=inputs, loss=loss)
        old_lr = optimizer.param_groups[0]["lr"]
        learning_rate_scheduler.step(loss.detach().item(), epoch=step)
        new_lr = optimizer.param_groups[0]["lr"]

        if new_lr != old_lr:
            logging.info(f"Learning rate changed from {old_lr} to {new_lr} at step {step}")
            logger.log_metrics(step, {"learning_rate": new_lr})

    def log_step(step, group):
        """Log metrics to MLflow. 'group' selects cheap vs expensive metrics."""
        metrics = training_metric_tracker.get_metrics(group)
        logger.log_metrics(step, metrics)


    eval_inputs, eval_labels = generate(cfg.training.num_steps)

    def evaluate():
        """Evaluate model on fixed data."""
        predictive_model.eval()
        outputs = predictive_model(eval_inputs)
        loss = get_loss(outputs, eval_labels)
        return float(loss.detach().item())

    def add_key_prefix(d, prefix):
        """straightforward util for naming consistency in logged metrics"""
        return {f"{prefix}/{k}": v for k, v in d.items()}

    def eval_step(step):
        """Run evaluation and log metrics."""
        loss = evaluate()
        eval_metric_tracker.step(loss=loss)
        metrics = eval_metric_tracker.get_metrics()
        metrics = add_key_prefix(metrics, "eval")
        logger.log_metrics(step, metrics)

    def activation_tracker_step(step):
        """
        analyze/track activations.

        The key research component: we generate sequences with full
        history including the generator belief states, run them through the model,
        cache activations to analyze how well the transformer's internal
        representations match the HMM's belief states.

        This section will be heavily notated, since it's the most
        conceptually rich part of the training loop.
        """

        predictive_model.eval()

        # This generates token sequence inputs/outputs along with:
        # 1) the ground truth belief states associated with each token
        # 2) the ground truth prefix probabilities
        # Both of these are calculated from the generative process
        outs = generate_data_batch_with_full_history(
            _expand_init_state(
                generative_process.initial_state,
                int(cfg.training.batch_size * cfg.training.validation_multiplier),
            ),
            generative_process,
            int(cfg.training.batch_size * cfg.training.validation_multiplier),
            sequence_len,
            jax.random.key(step),
            device=device_arg,
            bos_token=cfg.generative_process.bos_token,
        )

        inputs = outs["inputs"]
        prefix_probs = outs["prefix_probabilities"]

        # Run model and cache activations.
        # Different models produce different activation keys:
        # - HookedTransformer: many keys, we filter for residual stream ("resid")
        # - Custom model (in this case RNN): keep all keys from run_with_cache
        _, act_cache = predictive_model.run_with_cache(inputs)
        if isinstance(predictive_model, HookedTransformer):
            act_cache = {k: v.detach().cpu() for k, v in act_cache.items() if "resid" in k}
        else:
            act_cache = {k: v.detach().cpu() for k, v in act_cache.items()}

        # activation_tracker.analyze returns several things:
        # scalars:
        #       used for logging numeric metrics like # of PCA components to x% variance
        # projections:
        #        used for additional project specific analysis
        # visualizations:
        #     used for saving visualizations created by the activation tracker itself

        # here we are relying on cfg.activation_tracker to specify what analyses to run
        # a separate tutotrial will go over bespokse analyses/visualizations
        
        scalars, _, visualizations = activation_tracker.analyze(
            inputs=inputs,
            beliefs=outs["belief_states"],
            probs=prefix_probs,
            activations=act_cache,
            step=step,
        )

        # Save and log visualizations
        visualization_paths = activation_tracker.save_visualizations(
            visualizations, Path(visualization_path.name), step
        )
        for key, path in visualization_paths.items():
            logger.log_artifact(str(path), artifact_path=f"activation_plots/{key.split('/')[0]}")

        scalars = add_key_prefix(dict(scalars), "activations")
        logger.log_metrics(step, scalars)

    def checkpoint_step(step):
        """Save model weights to MLflow."""
        persister.save_weights(predictive_model, step)

    # ==========================================================================
    # TRAINING LOOP
    # ==========================================================================

    for step in tqdm.tqdm(range(cfg.training.num_steps + 1)):
        if step == 0:
            initial_loss = evaluate()
            training_metric_tracker.context.loss = initial_loss
            eval_metric_tracker.context.loss = initial_loss
            activation_tracker_step(step)
        else:
            train_step(step)

            #What counts as "cheap" vs "expensive" logging is in the metric tracker config
            if step % cfg.training.log_cheap_every == 0:
                log_step(step, "cheap")

            if step % cfg.training.log_expensive_every == 0:
                log_step(step, "expensive")
                activation_tracker_step(step)

            if step % cfg.training.evaluate_every == 0:
                eval_step(step)

            if step % cfg.training.checkpoint_every == 0:
                checkpoint_step(step)

    # ==========================================================================
    # FINAL MODEL REGISTRATION
    # ==========================================================================
    registered_model_name = cfg.predictive_model.name or "test_model"
    sample_inputs = generate(0)[0]
    step += 1
    persister.save_model_to_registry(
        predictive_model, registered_model_name, model_inputs=sample_inputs, step=step
    )

    visualization_path.cleanup()


if __name__ == "__main__":
    main()
