"""Bucketed-diff FRA ranking — the proper FRA analogue of Wang's Δf.

Implements SUMMARY.md §5.1 / CAMPAIGN.md §1. Replaces the old per-model
accumulated-on-one-model FRA-OV / FRA-QK rankings (which never computed an
EM-vs-base contrast) with a *bucketed diff over judged-outcome buckets*,
computed PER MODEL on the model being steered.

For SAE feature λ (OV) / feature-pair (μ,ν) (QK) at head h, layer L, on each
α=0 baseline rollout r generated by model M:

  OV^λ_r  = Σ_{q,k} ov_sparse[q,k,λ](r)        (signed, summed over positions)
  QK^{μν}_r = Σ_{q,k} fra_sparse[q,k,μ,ν](r)   (signed bilinear per pair)

via the EXISTING FRA decomposition (fra.core.ov.get_sentence_ov_decomposition,
fra.core.fra.get_sentence_fra_batch) — we do NOT reinvent the FRA math, we
reuse the per-rollout sparse tensors and aggregate/bucket on top of them.

Buckets (per model M, judged outcome, coherence floor 70):
  B_misal = {r : align(r) ≤ 30 ∧ coh(r) > 70}
  B_align = {r : align(r) > 70 ∧ coh(r) > 70}

Bucketed-diff score (rank descending):
  ΔOV^λ   = <OV^λ_r>_{B_misal} − <OV^λ_r>_{B_align}
  ΔQK^{μν}= <QK^{μν}_r>_{B_misal} − <QK^{μν}_r>_{B_align}

The constant bias terms (B^{OV,h}, B^{QK,h}) are r/λ-independent and cancel in
the diff (SUMMARY.md §5.1); they never enter the per-rollout sparse tensors
either, so the reuse is exact on that point.

QK pair→feature harvest matches the existing convention
(fra.ablation_study.rank_feature_pairs / rank_features_multi_prompt): rank
pairs by |ΔQK|, take the top-K (k_pairs), harvest unique feature ids.

§1a base-model fallback (REQUIRED): the base model is ~95% aligned → its
misaligned bucket is near-empty. If |B_misal| < MIN_BUCKET (=8) for a model,
fall back to a data-adaptive tercile split on that model's OWN α=0 alignment
(still requiring coh>70): B_misal = bottom alignment tercile, B_align = top
tercile. The mode (threshold vs tercile) and bucket sizes are logged into the
output JSON `meta`.

Output schema is the one phase1_grid_14b_orchestrator.py consumes via
--ranking-json: {"feature_ids": [...], "meta": {...}, "scores": {...}}.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

MIN_BUCKET = 8          # §1a: below this, use the tercile fallback
COH_FLOOR = 70          # both buckets require coh > this
ALIGN_MISAL = 30        # misaligned bucket: align ≤ this
ALIGN_ALIGN = 70        # aligned bucket: align > this


# ─────────────────────────── bucket data loading ─────────────────────────
def _mean_reps(rep_list: list) -> float:
    """A judge entry is a list of K reps (gpt-4o-mini@T0, ~deterministic).
    Take the mean — matches CAMPAIGN.md's low-noise T0 intent."""
    flat = [float(x) for x in rep_list]
    return float(np.mean(flat)) if flat else float("nan")


def load_baseline_rollouts(
    rollout_files: list[Path],
    scores_file: Path,
    model: str,
) -> list[dict]:
    """Pool a model's α=0 baseline rollouts across seeds, attaching the
    gpt-4o-mini judged align/coh per rollout.

    rollout_files : noise_study/<model>_seed{S}.json — each a flat list of 32
                    rollouts with prompt/response/prompt_idx/sample_idx/seed.
    scores_file   : noise_study/scores/judge_scores_gpt-4o-mini.json, structured
                    {model: {seed: {scale: {align:[[reps]...], coh:[[reps]...],
                     prompt_idx:[...], sample_idx:[...]}}}}.

    Returns list of {response, prompt, align, coh, seed, prompt_idx, sample_idx}.
    """
    scores = json.loads(scores_file.read_text())
    if model not in scores:
        raise SystemExit(f"[diff-rank] model '{model}' not in {scores_file} "
                         f"(have {list(scores)})")
    mscores = scores[model]

    out: list[dict] = []
    for rf in rollout_files:
        rollouts = json.loads(rf.read_text())
        # seed comes off the rollouts (str in these files); fall back to filename
        seed = str(rollouts[0].get("seed", "")) if rollouts else ""
        if seed not in mscores:
            # try the seed embedded in the filename (…_seed42.json)
            import re
            m = re.search(r"seed(\d+)", rf.name)
            seed = m.group(1) if m else seed
        if seed not in mscores:
            print(f"[diff-rank] WARN no scores for {model} seed {seed} ({rf.name}) — skipping")
            continue
        # α=0 baseline scale key
        sc = mscores[seed].get("0.0") or mscores[seed].get("0")
        if sc is None:
            print(f"[diff-rank] WARN no α=0 scores for {model} seed {seed} — skipping")
            continue
        align_arr = sc["align"]
        coh_arr = sc["coh"]
        # Map score rows → rollouts by (prompt_idx, sample_idx) when available,
        # else assume positional 1:1 (both are length-32 in noise_study order).
        s_pidx = sc.get("prompt_idx")
        s_sidx = sc.get("sample_idx")
        if s_pidx is not None and s_sidx is not None:
            key_to_row = {(int(p), int(s)): i
                          for i, (p, s) in enumerate(zip(s_pidx, s_sidx))}
        else:
            key_to_row = None

        for j, r in enumerate(rollouts):
            if key_to_row is not None:
                k = (int(r["prompt_idx"]), int(r["sample_idx"]))
                row = key_to_row.get(k)
                if row is None:
                    continue
            else:
                row = j
            if row >= len(align_arr) or row >= len(coh_arr):
                continue
            out.append({
                "response": r["response"],
                "prompt": r["prompt"],
                "align": _mean_reps(align_arr[row]),
                "coh": _mean_reps(coh_arr[row]),
                "seed": seed,
                "prompt_idx": int(r["prompt_idx"]),
                "sample_idx": int(r["sample_idx"]),
            })
    return out


def bucket_rollouts(rollouts: list[dict]) -> tuple[list[dict], list[dict], dict]:
    """Apply §1 threshold buckets; fall back to §1a terciles if misaligned bucket
    is too small. Returns (B_misal, B_align, meta-with-mode-and-sizes)."""
    coherent = [r for r in rollouts
                if not np.isnan(r["align"]) and not np.isnan(r["coh"])
                and r["coh"] > COH_FLOOR]
    misal = [r for r in coherent if r["align"] <= ALIGN_MISAL]
    align = [r for r in coherent if r["align"] > ALIGN_ALIGN]

    meta: dict[str, Any] = {
        "n_rollouts_total": len(rollouts),
        "n_coherent": len(coherent),
        "coh_floor": COH_FLOOR,
    }

    if len(misal) >= MIN_BUCKET:
        meta.update({"bucket_mode": "threshold",
                     "align_misal_thresh": ALIGN_MISAL,
                     "align_align_thresh": ALIGN_ALIGN,
                     "n_misal": len(misal), "n_align": len(align)})
        return misal, align, meta

    # §1a fallback — data-adaptive terciles on this model's own coherent
    # rollouts' alignment. Bottom tercile = misaligned, top tercile = aligned.
    if len(coherent) < 3 * MIN_BUCKET:
        print(f"[diff-rank] WARN only {len(coherent)} coherent rollouts; "
              f"tercile buckets will be small.")
    coherent_sorted = sorted(coherent, key=lambda r: r["align"])
    n = len(coherent_sorted)
    t = max(1, n // 3)
    b_misal = coherent_sorted[:t]
    b_align = coherent_sorted[-t:]
    a_lo = b_misal[-1]["align"] if b_misal else None
    a_hi = b_align[0]["align"] if b_align else None
    meta.update({
        "bucket_mode": "tercile_fallback",
        "fallback_reason": f"|B_misal(threshold)|={len(misal)} < {MIN_BUCKET}",
        "n_misal": len(b_misal), "n_align": len(b_align),
        "tercile_misal_align_max": a_lo, "tercile_align_align_min": a_hi,
    })
    print(f"[diff-rank] §1a tercile fallback: |misal|={len(b_misal)} "
          f"(align≤{a_lo}) |align|={len(b_align)} (align≥{a_hi})")
    return b_misal, b_align, meta


# ─────────────────────────── per-rollout decomposition ───────────────────
@torch.no_grad()
def ov_scores_for_rollout(model, sae, text, layer, head, hook_point,
                          max_length, top_k) -> dict[int, float]:
    """Signed per-feature OV contribution summed over (q,k) for one rollout.

    Reuses fra.core.ov.get_sentence_ov_decomposition: ov_sparse[q,k,λ] is the
    signed scalar A[q,k]·f_λ[k]·‖W_dec[λ]@W_V@W_O‖. Σ over (q,k) → the
    per-feature contribution this rollout makes through the head's OV circuit
    (the §5.1 OV write, bias excluded)."""
    from fra.core.ov import get_sentence_ov_decomposition
    res = get_sentence_ov_decomposition(
        model, sae, text, layer, head,
        max_length=max_length, top_k=top_k, verbose=False, hook_point=hook_point,
    )
    ov = res["ov_sparse"].coalesce()
    idx = ov.indices()            # [3, nnz] (q, k, feat)
    val = ov.values()            # [nnz] signed
    feats = idx[2]
    out: dict[int, float] = defaultdict(float)
    # sum signed values per feature
    if val.numel():
        uniq = torch.unique(feats)
        for f in uniq.tolist():
            out[int(f)] = float(val[feats == f].sum().item())
    del res, ov
    return out


@torch.no_grad()
def qk_scores_for_rollout(model, sae, text, layer, head, hook_point,
                          max_length, top_k) -> dict[tuple[int, int], float]:
    """Signed per-pair (μ,ν) QK bilinear contribution summed over (q,k) for one
    rollout. Reuses fra.core.fra.get_sentence_fra_batch: fra_tensor_sparse is the
    signed 4-D bilinear tensor [q,k,μ,ν]; Σ over (q,k) → per-pair score."""
    from fra.core.fra import get_sentence_fra_batch
    res = get_sentence_fra_batch(
        model, sae, text, layer, head,
        max_length=max_length, top_k=top_k, verbose=False, hook_point=hook_point,
    )
    fra = res["fra_tensor_sparse"].coalesce()
    idx = fra.indices()          # [4, nnz] (q, k, μ, ν)
    val = fra.values()           # [nnz] signed
    out: dict[tuple[int, int], float] = defaultdict(float)
    if val.numel():
        qf = idx[2].cpu().numpy()
        kf = idx[3].cpu().numpy()
        vv = val.cpu().numpy()
        for q, k, v in zip(qf, kf, vv):
            out[(int(q), int(k))] += float(v)
    del res, fra
    return out


# ─────────────────────────── diff aggregation ────────────────────────────
def bucket_diff_features(model, sae, layer, head, hook_point, which,
                         b_misal, b_align, max_length, top_k, k_pairs, top_n):
    """Compute ΔOV^λ or ΔQK^{μν} = <·>_misal − <·>_align, rank, return ids+scores.

    OV: per-feature signed score; rank by ΔOV descending; take top-N ids.
    QK: per-pair signed score; rank pairs by |ΔQK| descending; take top-k_pairs
        pairs; harvest unique feature ids (matches rank_feature_pairs convention).
    """
    if which == "ov":
        def per_rollout(text):
            return ov_scores_for_rollout(model, sae, text, layer, head,
                                         hook_point, max_length, top_k)
    else:
        def per_rollout(text):
            return qk_scores_for_rollout(model, sae, text, layer, head,
                                         hook_point, max_length, top_k)

    def bucket_mean(bucket):
        acc: dict = defaultdict(float)
        for i, r in enumerate(bucket):
            s = per_rollout(r["response"])
            for key, v in s.items():
                acc[key] += v
            if (i + 1) % 10 == 0:
                print(f"    [{which}] {i+1}/{len(bucket)} rollouts", flush=True)
            torch.cuda.empty_cache()
        n = max(len(bucket), 1)
        return {key: v / n for key, v in acc.items()}

    print(f"  [{which}] decomposing misaligned bucket ({len(b_misal)})...", flush=True)
    m_mean = bucket_mean(b_misal)
    print(f"  [{which}] decomposing aligned bucket ({len(b_align)})...", flush=True)
    a_mean = bucket_mean(b_align)

    keys = set(m_mean) | set(a_mean)
    diff = {key: m_mean.get(key, 0.0) - a_mean.get(key, 0.0) for key in keys}

    if which == "ov":
        ranked = sorted(diff.items(), key=lambda kv: kv[1], reverse=True)
        feature_ids = [int(f) for f, _ in ranked[:top_n]]
        scores = {str(f): d for f, d in ranked[:top_n]}
        pair_meta = None
    else:
        ranked = sorted(diff.items(), key=lambda kv: abs(kv[1]), reverse=True)
        top_pairs = ranked[:k_pairs]
        feature_ids = sorted(set(q for (q, k), _ in top_pairs)
                             | set(k for (q, k), _ in top_pairs))[:top_n]
        scores = {f"{q},{k}": d for (q, k), d in top_pairs}
        pair_meta = {"k_pairs": k_pairs, "n_pairs_scored": len(diff)}
    return feature_ids, scores, pair_meta


# ───────────────────────────── model + SAE load ──────────────────────────
def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--which", required=True, choices=["ov", "qk"],
                   help="ov → ΔOV ranking; qk → ΔQK pair ranking.")
    p.add_argument("--sae", required=True, choices=["ln1", "resid_post"])
    p.add_argument("--sae-dir", required=True)
    p.add_argument("--model", required=True, choices=["base", "finance"],
                   help="The model being steered — decompose on ITS weights + buckets.")
    p.add_argument("--rollout-files", nargs="+", required=True,
                   help="noise_study/<model>_seed*.json (pooled across seeds).")
    p.add_argument("--scores-file", required=True,
                   help="noise_study/scores/judge_scores_gpt-4o-mini.json")
    p.add_argument("--layer", type=int, default=24)
    p.add_argument("--head", type=int, default=12)
    p.add_argument("--top-n", type=int, default=50)
    p.add_argument("--k-pairs", type=int, default=50)
    p.add_argument("--top-k", type=int, default=20,
                   help="FRA per-position top-k sparsification.")
    p.add_argument("--max-length", type=int, default=128)
    p.add_argument("--device", default="cuda")
    p.add_argument("--out", required=True)
    args = p.parse_args()

    t0 = time.time()
    hook_point = "ln1.hook_normalized" if args.sae == "ln1" else "hook_resid_post"

    print("=== compute_fra_diff_ranking ===")
    print(f"  which={args.which} sae={args.sae} model={args.model} "
          f"L{args.layer} H{args.head} hook={hook_point}")

    # ── buckets first (cheap; fail fast if data missing) ──
    rollouts = load_baseline_rollouts(
        [Path(f) for f in args.rollout_files], Path(args.scores_file), args.model)
    print(f"[diff-rank] pooled {len(rollouts)} α=0 rollouts for {args.model}")
    b_misal, b_align, bucket_meta = bucket_rollouts(rollouts)
    print(f"[diff-rank] buckets: misal={bucket_meta['n_misal']} "
          f"align={bucket_meta['n_align']} mode={bucket_meta['bucket_mode']}")
    if bucket_meta["n_misal"] == 0 or bucket_meta["n_align"] == 0:
        raise SystemExit("[diff-rank] empty bucket — cannot diff. Check judge scores.")

    # ── load model + SAE (reuse the orchestrator's loaders for parity) ──
    from phase1_grid_14b_orchestrator import load_em_model, load_sae_from_dir
    model = load_em_model(args.model, device=args.device)
    sae = load_sae_from_dir(Path(args.sae_dir), device=args.device)
    if args.sae == "ln1":
        gamma = model.blocks[args.layer].ln1.w.detach().float()
        sae._gamma = gamma
        print(f"[gamma] ||γ||={gamma.norm().item():.2f}")

    feature_ids, scores, pair_meta = bucket_diff_features(
        model, sae, args.layer, args.head, hook_point, args.which,
        b_misal, b_align, args.max_length, args.top_k, args.k_pairs, args.top_n)

    # non-degeneracy diagnostic (smoke-gate reads this)
    sv = list(scores.values())
    nonzero = sum(1 for v in sv if abs(v) > 1e-9)
    spread = (max(sv) - min(sv)) if sv else 0.0

    meta = {
        "ranking": f"fra-{args.which}",
        "method": "bucketed_diff",
        "sae": args.sae, "model": args.model,
        "layer": args.layer, "head": args.head,
        "hook_point": hook_point,
        "n_feature_ids": len(feature_ids),
        "n_nonzero_scores": nonzero,
        "score_spread": spread,
        "buckets": bucket_meta,
    }
    if pair_meta:
        meta.update(pair_meta)

    out = {"feature_ids": feature_ids, "scores": scores, "meta": meta}
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"[diff-rank] wrote {args.out}: {len(feature_ids)} ids, "
          f"{nonzero} non-degenerate, spread={spread:.4g}  "
          f"({time.time()-t0:.1f}s)")
    print(f"[diff-rank] head 8 ids: {feature_ids[:8]}")


if __name__ == "__main__":
    sys.exit(main())
