"""Bucketed-diff FRA ranking — the proper FRA analogue of Wang's Δf.

Implements SUMMARY.md §5.1 / CAMPAIGN.md §1. Replaces the old per-model
accumulated-on-one-model FRA-OV / FRA-QK rankings (which never computed an
EM-vs-base contrast) with a *bucketed diff over judged-outcome buckets*,
computed PER MODEL on the model being steered.

For SAE feature λ (OV) / feature-pair (μ,ν) (QK) at head h, layer L, on each
α=0 baseline rollout r generated by model M:

  OV^λ_r  = Σ_{q,k} ov_sparse[q,k,λ](r)        (signed, summed over positions)
  QK^{μν}_r = Σ_{q,k} fra_sparse[q,k,μ,ν](r)   (signed bilinear per pair)

via the EXISTING FRA decomposition (fra.core.ov.get_sentence_ov_decomposition,
fra.core.fra.get_sentence_fra_batch) — we do NOT reinvent the FRA math, we
reuse the per-rollout sparse tensors and aggregate/bucket on top of them.

Buckets (per model M, judged outcome, coherence floor 70):
  B_misal = {r : align(r) ≤ 30 ∧ coh(r) > 70}
  B_align = {r : align(r) > 70 ∧ coh(r) > 70}

Bucketed-diff score (rank descending):
  ΔOV^λ   = <OV^λ_r>_{B_misal} − <OV^λ_r>_{B_align}
  ΔQK^{μν}= <QK^{μν}_r>_{B_misal} − <QK^{μν}_r>_{B_align}

The constant bias terms (B^{OV,h}, B^{QK,h}) are r/λ-independent and cancel in
the diff (SUMMARY.md §5.1); they never enter the per-rollout sparse tensors
either, so the reuse is exact on that point.

QK pair→feature harvest matches the existing convention
(fra.ablation_study.rank_feature_pairs / rank_features_multi_prompt): rank
pairs by |ΔQK|, take the top-K (k_pairs), harvest unique feature ids.

§1a base-model fallback (REQUIRED): the base model is ~95% aligned → its
misaligned bucket is near-empty. If |B_misal| < MIN_BUCKET (=8) for a model,
fall back to a data-adaptive tercile split on that model's OWN α=0 alignment
(still requiring coh>70): B_misal = bottom alignment tercile, B_align = top
tercile. The mode (threshold vs tercile) and bucket sizes are logged into the
output JSON `meta`.

Output schema is the one phase1_grid_14b_orchestrator.py consumes via
--ranking-json: {"feature_ids": [...], "meta": {...}, "scores": {...}}.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

MIN_BUCKET = 8          # §1a: below this, use the tercile fallback
COH_FLOOR = 70          # both buckets require coh > this
ALIGN_MISAL = 30        # misaligned bucket: align ≤ this
ALIGN_ALIGN = 70        # aligned bucket: align > this


# ─────────────────────────── bucket data loading ─────────────────────────
def _mean_reps(rep_list: list) -> float:
    """A judge entry is a list of K reps (gpt-4o-mini@T0, ~deterministic).
    Take the mean — matches CAMPAIGN.md's low-noise T0 intent."""
    flat = [float(x) for x in rep_list]
    return float(np.mean(flat)) if flat else float("nan")


def load_baseline_rollouts(
    rollout_files: list[Path],
    scores_file: Path,
    model: str,
) -> list[dict]:
    """Pool a model's α=0 baseline rollouts across seeds, attaching the
    gpt-4o-mini judged align/coh per rollout.

    rollout_files : noise_study/<model>_seed{S}.json — each a flat list of 32
                    rollouts with prompt/response/prompt_idx/sample_idx/seed.
    scores_file   : noise_study/scores/judge_scores_gpt-4o-mini.json, structured
                    {model: {seed: {scale: {align:[[reps]...], coh:[[reps]...],
                     prompt_idx:[...], sample_idx:[...]}}}}.

    Returns list of {response, prompt, align, coh, seed, prompt_idx, sample_idx}.
    """
    scores = json.loads(scores_file.read_text())
    if model not in scores:
        raise SystemExit(f"[diff-rank] model '{model}' not in {scores_file} "
                         f"(have {list(scores)})")
    mscores = scores[model]

    out: list[dict] = []
    for rf in rollout_files:
        rollouts = json.loads(rf.read_text())
        if not rollouts:
            continue
        # Only consume this model's rollout files. The entries carry a 'model'
        # field; in model-diff mode BOTH models' files are passed, so skip the
        # other model's (else we'd pair its text with this model's scores).
        rf_model = str(rollouts[0].get("model", "")).strip()
        if rf_model and rf_model != model:
            continue
        # seed comes off the rollouts (str in these files); fall back to filename
        seed = str(rollouts[0].get("seed", "")) if rollouts else ""
        if seed not in mscores:
            # try the seed embedded in the filename (…_seed42.json)
            import re
            m = re.search(r"seed(\d+)", rf.name)
            seed = m.group(1) if m else seed
        if seed not in mscores:
            print(f"[diff-rank] WARN no scores for {model} seed {seed} ({rf.name}) — skipping")
            continue
        # α=0 baseline scale key
        sc = mscores[seed].get("0.0") or mscores[seed].get("0")
        if sc is None:
            print(f"[diff-rank] WARN no α=0 scores for {model} seed {seed} — skipping")
            continue
        align_arr = sc["align"]
        coh_arr = sc["coh"]
        # Map score rows → rollouts by (prompt_idx, sample_idx) when available,
        # else assume positional 1:1 (both are length-32 in noise_study order).
        s_pidx = sc.get("prompt_idx")
        s_sidx = sc.get("sample_idx")
        if s_pidx is not None and s_sidx is not None:
            key_to_row = {(int(p), int(s)): i
                          for i, (p, s) in enumerate(zip(s_pidx, s_sidx))}
        else:
            key_to_row = None

        for j, r in enumerate(rollouts):
            if key_to_row is not None:
                k = (int(r["prompt_idx"]), int(r["sample_idx"]))
                row = key_to_row.get(k)
                if row is None:
                    continue
            else:
                row = j
            if row >= len(align_arr) or row >= len(coh_arr):
                continue
            out.append({
                "response": r["response"],
                "prompt": r["prompt"],
                "align": _mean_reps(align_arr[row]),
                "coh": _mean_reps(coh_arr[row]),
                "seed": seed,
                "prompt_idx": int(r["prompt_idx"]),
                "sample_idx": int(r["sample_idx"]),
            })
    return out


def bucket_rollouts(rollouts: list[dict]) -> tuple[list[dict], list[dict], dict]:
    """Apply §1 threshold buckets; fall back to §1a terciles if misaligned bucket
    is too small. Returns (B_misal, B_align, meta-with-mode-and-sizes)."""
    coherent = [r for r in rollouts
                if not np.isnan(r["align"]) and not np.isnan(r["coh"])
                and r["coh"] > COH_FLOOR]
    misal = [r for r in coherent if r["align"] <= ALIGN_MISAL]
    align = [r for r in coherent if r["align"] > ALIGN_ALIGN]

    meta: dict[str, Any] = {
        "n_rollouts_total": len(rollouts),
        "n_coherent": len(coherent),
        "coh_floor": COH_FLOOR,
    }

    if len(misal) >= MIN_BUCKET:
        meta.update({"bucket_mode": "threshold",
                     "align_misal_thresh": ALIGN_MISAL,
                     "align_align_thresh": ALIGN_ALIGN,
                     "n_misal": len(misal), "n_align": len(align)})
        return misal, align, meta

    # §1a fallback — data-adaptive terciles on this model's own coherent
    # rollouts' alignment. Bottom tercile = misaligned, top tercile = aligned.
    if len(coherent) < 3 * MIN_BUCKET:
        print(f"[diff-rank] WARN only {len(coherent)} coherent rollouts; "
              f"tercile buckets will be small.")
    coherent_sorted = sorted(coherent, key=lambda r: r["align"])
    n = len(coherent_sorted)
    t = max(1, n // 3)
    b_misal = coherent_sorted[:t]
    b_align = coherent_sorted[-t:]
    a_lo = b_misal[-1]["align"] if b_misal else None
    a_hi = b_align[0]["align"] if b_align else None
    meta.update({
        "bucket_mode": "tercile_fallback",
        "fallback_reason": f"|B_misal(threshold)|={len(misal)} < {MIN_BUCKET}",
        "n_misal": len(b_misal), "n_align": len(b_align),
        "tercile_misal_align_max": a_lo, "tercile_align_align_min": a_hi,
    })
    print(f"[diff-rank] §1a tercile fallback: |misal|={len(b_misal)} "
          f"(align≤{a_lo}) |align|={len(b_align)} (align≥{a_hi})")
    return b_misal, b_align, meta


# ─────────────────────────── per-rollout decomposition ───────────────────
@torch.no_grad()
def ov_scores_for_rollout(model, sae, text, layer, head, hook_point,
                          max_length, top_k) -> dict[int, float]:
    """Signed per-feature OV contribution summed over (q,k) for one rollout.

    Reuses fra.core.ov.get_sentence_ov_decomposition: ov_sparse[q,k,λ] is the
    signed scalar A[q,k]·f_λ[k]·‖W_dec[λ]@W_V@W_O‖. Σ over (q,k) → the
    per-feature contribution this rollout makes through the head's OV circuit
    (the §5.1 OV write, bias excluded)."""
    from fra.core.ov import get_sentence_ov_decomposition
    res = get_sentence_ov_decomposition(
        model, sae, text, layer, head,
        max_length=max_length, top_k=top_k, verbose=False, hook_point=hook_point,
    )
    ov = res["ov_sparse"].coalesce()
    idx = ov.indices()            # [3, nnz] (q, k, feat)
    val = ov.values()            # [nnz] signed
    feats = idx[2]
    out: dict[int, float] = defaultdict(float)
    # sum signed values per feature
    if val.numel():
        uniq = torch.unique(feats)
        for f in uniq.tolist():
            out[int(f)] = float(val[feats == f].sum().item())
    del res, ov
    return out


@torch.no_grad()
def qk_scores_for_rollout(model, sae, text, layer, head, hook_point,
                          max_length, top_k) -> dict[tuple[int, int], float]:
    """Signed per-pair (μ,ν) QK bilinear contribution summed over (q,k) for one
    rollout. Reuses fra.core.fra.get_sentence_fra_batch: fra_tensor_sparse is the
    signed 4-D bilinear tensor [q,k,μ,ν]; Σ over (q,k) → per-pair score."""
    from fra.core.fra import get_sentence_fra_batch
    res = get_sentence_fra_batch(
        model, sae, text, layer, head,
        max_length=max_length, top_k=top_k, verbose=False, hook_point=hook_point,
    )
    fra = res["fra_tensor_sparse"].coalesce()
    idx = fra.indices()          # [4, nnz] (q, k, μ, ν)
    val = fra.values()           # [nnz] signed
    out: dict[tuple[int, int], float] = defaultdict(float)
    if val.numel():
        qf = idx[2].cpu().numpy()
        kf = idx[3].cpu().numpy()
        vv = val.cpu().numpy()
        for q, k, v in zip(qf, kf, vv):
            out[(int(q), int(k))] += float(v)
    del res, fra
    return out


@torch.no_grad()
def wang_scores_for_rollout(model, sae, text, layer, hook_point,
                            max_length, top_k=None) -> dict[int, float]:
    """Wang-style attribution: mean SAE *encoder activation* f^λ over the
    rollout's answer-token positions, per feature. The 2×2 partner of the
    OV/QK FRA attribution — same bucketing, different attribution quantity.

    Forward the rollout, cache the SAE hookpoint, encode (the ln1 adapter
    applies γ post-gain inside sae.encode), mean over positions. No top-k
    sparsification here: Wang's Δf uses the dense encoder mean (sparsifying
    would bias toward whichever features happen to fire per-position).
    """
    device = next(model.parameters()).device
    tokens = model.tokenizer.encode(text)
    if max_length is not None and len(tokens) > max_length:
        tokens = tokens[:max_length]
    if len(tokens) == 0:
        return {}
    tt = torch.tensor(tokens).unsqueeze(0).to(device)
    hn = f"blocks.{layer}.{hook_point}"
    _, cache = model.run_with_cache(tt, names_filter=[hn])
    act = cache[hn].squeeze(0)
    if act.dim() == 3:
        act = act.flatten(-2, -1)
    feats = sae.encode(act).float()            # [seq, d_sae] (γ applied for ln1)
    mean_f = feats.mean(dim=0)                  # [d_sae]
    nz = torch.where(mean_f.abs() > 1e-12)[0]
    out = {int(i): float(mean_f[i].item()) for i in nz.tolist()}
    del cache
    return out


# ─────────────────────────── diff aggregation ────────────────────────────
def _per_rollout_fn(model, sae, layer, head, hook_point, attribution,
                    max_length, top_k):
    """Return a closure text→{key: signed score} for the chosen attribution.
    attribution ∈ {ov, qk, wang}; key is a feature id (ov/wang) or a (μ,ν)
    pair (qk)."""
    if attribution == "ov":
        return lambda text: ov_scores_for_rollout(model, sae, text, layer, head,
                                                  hook_point, max_length, top_k)
    if attribution == "qk":
        return lambda text: qk_scores_for_rollout(model, sae, text, layer, head,
                                                  hook_point, max_length, top_k)
    if attribution == "wang":
        return lambda text: wang_scores_for_rollout(model, sae, text, layer,
                                                    hook_point, max_length)
    raise ValueError(f"unknown attribution {attribution}")


def _set_mean(per_rollout, bucket, label):
    """Mean of per-rollout score dicts over a bucket (key→mean signed score)."""
    acc: dict = defaultdict(float)
    for i, r in enumerate(bucket):
        for key, v in per_rollout(r["response"]).items():
            acc[key] += v
        if (i + 1) % 10 == 0:
            print(f"    [{label}] {i+1}/{len(bucket)} rollouts", flush=True)
        torch.cuda.empty_cache()
    n = max(len(bucket), 1)
    return {key: v / n for key, v in acc.items()}


def _rank_from_diff(diff, attribution, k_pairs, top_n):
    """Common ranking from a diff dict. ov/wang → per-feature signed, rank desc.
    qk → per-pair |Δ| desc, top-k_pairs, harvest unique feature ids."""
    if attribution in ("ov", "wang"):
        ranked = sorted(diff.items(), key=lambda kv: kv[1], reverse=True)
        feature_ids = [int(f) for f, _ in ranked[:top_n]]
        scores = {str(f): d for f, d in ranked[:top_n]}
        return feature_ids, scores, None
    ranked = sorted(diff.items(), key=lambda kv: abs(kv[1]), reverse=True)
    top_pairs = ranked[:k_pairs]
    feature_ids = sorted(set(q for (q, k), _ in top_pairs)
                         | set(k for (q, k), _ in top_pairs))[:top_n]
    scores = {f"{q},{k}": d for (q, k), d in top_pairs}
    return feature_ids, scores, {"k_pairs": k_pairs, "n_pairs_scored": len(diff)}


def bucket_diff_features(model, sae, layer, head, hook_point, attribution,
                         b_misal, b_align, max_length, top_k, k_pairs, top_n):
    """Outcome-bucket diff: <·>_misal − <·>_align on ONE model. attribution ∈
    {ov, qk, wang}."""
    per_rollout = _per_rollout_fn(model, sae, layer, head, hook_point,
                                  attribution, max_length, top_k)
    print(f"  [{attribution}] misaligned bucket ({len(b_misal)})...", flush=True)
    m_mean = _set_mean(per_rollout, b_misal, attribution)
    print(f"  [{attribution}] aligned bucket ({len(b_align)})...", flush=True)
    a_mean = _set_mean(per_rollout, b_align, attribution)
    keys = set(m_mean) | set(a_mean)
    diff = {k: m_mean.get(k, 0.0) - a_mean.get(k, 0.0) for k in keys}
    return _rank_from_diff(diff, attribution, k_pairs, top_n)


# (model-identity diff is inlined in main(): a single 80GB GPU can't hold two
#  14B models, so finance is decomposed + freed before base loads.)


def _attach_gamma(model, sae, layer, sae_family):
    if sae_family == "ln1":
        gamma = model.blocks[layer].ln1.w.detach().float()
        sae._gamma = gamma
        print(f"[gamma] ||γ||={gamma.norm().item():.2f}")


# ───────────────────────────── model + SAE load ──────────────────────────
def main():
    p = argparse.ArgumentParser(description=__doc__)
    # --which is the back-compat alias for the main campaign (ov|qk). --attribution
    # is the general selector (adds wang). Exactly one of them sets the attribution.
    p.add_argument("--which", choices=["ov", "qk"],
                   help="back-compat alias → --attribution {ov,qk}.")
    p.add_argument("--attribution", choices=["ov", "qk", "wang"],
                   help="ov/qk = FRA attribution; wang = mean encoder f^λ.")
    p.add_argument("--diff-mode", choices=["bucket", "model"], default="bucket",
                   help="bucket = outcome-bucket diff (per-model, coh>70, §1a "
                        "fallback); model = finance−base over all answer tokens "
                        "(Variant B, no coh gate; one ranking steers both cells).")
    p.add_argument("--sae", required=True, choices=["ln1", "resid_post"])
    p.add_argument("--sae-dir", required=True)
    p.add_argument("--model", choices=["base", "finance"],
                   help="bucket mode: the model being steered (decompose on its "
                        "weights+buckets). Ignored for diff-mode=model.")
    p.add_argument("--rollout-files", nargs="+", required=True,
                   help="bucket: noise_study/<model>_seed*.json. model: pass BOTH "
                        "models' files (auto-split by the 'model' field).")
    p.add_argument("--scores-file", required=True)
    p.add_argument("--layer", type=int, default=24)
    p.add_argument("--head", type=int, default=12)
    p.add_argument("--top-n", type=int, default=50)
    p.add_argument("--k-pairs", type=int, default=50)
    p.add_argument("--top-k", type=int, default=20)
    p.add_argument("--max-length", type=int, default=128)
    p.add_argument("--device", default="cuda")
    p.add_argument("--out", required=True)
    args = p.parse_args()

    attribution = args.attribution or args.which
    if attribution is None:
        raise SystemExit("set --attribution {ov,qk,wang} (or --which {ov,qk})")
    if args.diff_mode == "bucket" and args.model is None:
        raise SystemExit("--diff-mode bucket requires --model")

    t0 = time.time()
    hook_point = "ln1.hook_normalized" if args.sae == "ln1" else "hook_resid_post"
    rfiles = [Path(f) for f in args.rollout_files]
    sfile = Path(args.scores_file)

    print("=== compute_fra_diff_ranking ===")
    print(f"  attribution={attribution} diff_mode={args.diff_mode} sae={args.sae} "
          f"model={args.model} L{args.layer} H{args.head} hook={hook_point}")

    from phase1_grid_14b_orchestrator import load_em_model, load_sae_from_dir

    if args.diff_mode == "bucket":
        # ── per-model outcome-bucket diff (main campaign + Variant A) ──
        rollouts = load_baseline_rollouts(rfiles, sfile, args.model)
        print(f"[diff-rank] pooled {len(rollouts)} α=0 rollouts for {args.model}")
        b_misal, b_align, bucket_meta = bucket_rollouts(rollouts)
        print(f"[diff-rank] buckets: misal={bucket_meta['n_misal']} "
              f"align={bucket_meta['n_align']} mode={bucket_meta['bucket_mode']}")
        if bucket_meta["n_misal"] == 0 or bucket_meta["n_align"] == 0:
            raise SystemExit("[diff-rank] empty bucket — cannot diff.")
        model = load_em_model(args.model, device=args.device)
        sae = load_sae_from_dir(Path(args.sae_dir), device=args.device)
        _attach_gamma(model, sae, args.layer, args.sae)
        feature_ids, scores, pair_meta = bucket_diff_features(
            model, sae, args.layer, args.head, hook_point, attribution,
            b_misal, b_align, args.max_length, args.top_k, args.k_pairs, args.top_n)
        method = "bucketed_diff"
        diff_meta = {"buckets": bucket_meta}
    else:
        # ── Variant B: finance−base model-identity diff (decompose each on its
        #    own weights). Load BOTH models; one ranking steers both cells. ──
        fin_rolls = load_baseline_rollouts(rfiles, sfile, "finance")
        base_rolls = load_baseline_rollouts(rfiles, sfile, "base")
        print(f"[diff-rank] model-diff: finance={len(fin_rolls)} base={len(base_rolls)} "
              f"α=0 rollouts (all answer tokens, no coh gate)")
        if not fin_rolls or not base_rolls:
            raise SystemExit("[diff-rank] need both finance and base rollouts for model-diff.")
        sae_dir = Path(args.sae_dir)
        fin_model = load_em_model("finance", device=args.device)
        fin_sae = load_sae_from_dir(sae_dir, device=args.device)
        _attach_gamma(fin_model, fin_sae, args.layer, args.sae)
        feature_ids = scores = pair_meta = None
        # decompose finance, free it, then base (one 80GB GPU can't hold two 14B)
        fin_pr = _per_rollout_fn(fin_model, fin_sae, args.layer, args.head,
                                 hook_point, attribution, args.max_length, args.top_k)
        print(f"  [{attribution}] finance rollouts ({len(fin_rolls)})...", flush=True)
        f_mean = _set_mean(fin_pr, fin_rolls, attribution + "/fin")
        del fin_model, fin_sae; torch.cuda.empty_cache()
        base_model = load_em_model("base", device=args.device)
        base_sae = load_sae_from_dir(sae_dir, device=args.device)
        _attach_gamma(base_model, base_sae, args.layer, args.sae)
        base_pr = _per_rollout_fn(base_model, base_sae, args.layer, args.head,
                                  hook_point, attribution, args.max_length, args.top_k)
        print(f"  [{attribution}] base rollouts ({len(base_rolls)})...", flush=True)
        b_mean = _set_mean(base_pr, base_rolls, attribution + "/base")
        keys = set(f_mean) | set(b_mean)
        diff = {k: f_mean.get(k, 0.0) - b_mean.get(k, 0.0) for k in keys}
        feature_ids, scores, pair_meta = _rank_from_diff(
            diff, attribution, args.k_pairs, args.top_n)
        method = "model_identity_diff"
        diff_meta = {"n_finance": len(fin_rolls), "n_base": len(base_rolls),
                     "coh_gate": False, "decomposition": "per_model_own_weights"}

    sv = list(scores.values())
    nonzero = sum(1 for v in sv if abs(v) > 1e-9)
    spread = (max(sv) - min(sv)) if sv else 0.0
    # `scores` holds per-FEATURE diffs for ov/wang, but per-PAIR diffs for qk
    # (the QK ranking harvests unique feature ids from top-K pairs). Label the
    # count by what it actually counts so the provenance column isn't misleading
    # (n_nonzero_scores=50 pairs vs n_feature_ids=22 features is NOT a contradiction).
    score_entry_kind = "pair" if attribution == "qk" else "feature"

    meta = {
        "ranking": f"{attribution}",
        "method": method,
        "diff_mode": args.diff_mode,
        "sae": args.sae, "model": args.model,
        "layer": args.layer, "head": args.head,
        "hook_point": hook_point,
        "n_feature_ids": len(feature_ids),
        "score_entry_kind": score_entry_kind,
        "n_nonzero_score_entries": nonzero,
        # back-compat alias (kept so older table builders don't KeyError); reads
        # as feature-count for ov/wang, pair-count for qk — see score_entry_kind.
        "n_nonzero_scores": nonzero,
        "score_spread": spread,
    }
    meta.update(diff_meta)
    if pair_meta:
        meta.update(pair_meta)

    out = {"feature_ids": feature_ids, "scores": scores, "meta": meta}
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"[diff-rank] wrote {args.out}: {len(feature_ids)} ids, "
          f"{nonzero} non-degenerate, spread={spread:.4g}  "
          f"({time.time()-t0:.1f}s)")
    print(f"[diff-rank] head 8 ids: {feature_ids[:8]}")


if __name__ == "__main__":
    sys.exit(main())
