name: lr_mix
instance:
  _target_: simplexity.generative_processes.builder.build_hidden_markov_model
  process_name: left_right_mix
  process_params:
    a: 0.2
    b: 0.2
  device: ${device}

base_vocab_size: ???
bos_token: ???
eos_token: null
vocab_size: ???
