name: hooked_transformer
instance:
  _target_: transformer_lens.HookedTransformer
  cfg:
    _target_: transformer_lens.HookedTransformerConfig
    d_model: 64
    d_head: 32
    n_heads: 2
    n_layers: 2
    n_ctx: 16
    d_mlp: 256
    d_vocab: ???
    act_fn: "gelu"
    normalization_type: "LN"
    device: ${device}
    seed: ${seed}

load_checkpoint_step: null
